development:
  adapter: sqlite3
  dbfile: db/dev.db

test:
  adapter: sqlite3
  dbfile: db/test.db

production:
  adapter: mysql
  database: ozarksvacationlink_com_prod
  username: railsprd
  password: railsprd  
  host: localhost
  timeout: 5000
